export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_USERS = 'GET_USERS';
export const USERS_LOADING = "USERS_LOADING";
export const USERS_LOADED = "USERS_LOADED";




/** ITEMS TYPES **/
export const ITEMS_LOADING = "ITEMS_LOADING";
export const ITEMS_LOADED = "ITEMS_LOADED";

/** ADMIN TYPES **/
export const ADMIN_CAMPAIGNS_LOADING = "ADMIN_CAMPAIGNS_LOADING";
export const ADMIN_CAMPAIGNS_LOADED = "ADMIN_CAMPAIGNS_LOADED";


export const ADMIN_SINGLECAMPAIGNS_LOADING= "ADMIN_SINGLECAMPAIGNS_LOADING";
export const ADMIN_SINGLECAMPAIGNS_LOADED= "ADMIN_SINGLECAMPAIGNS_LOADED";

export const ADMIN_FLAG_CAMPAIGNS_LOADING = "ADMIN_FLAG_CAMPAIGNS_LOADING";
export const ADMIN_FLAG_CAMPAIGNS_LOADED = "ADMIN_FLAG_CAMPAIGNS_LOADED";



export const ADMIN_BRAND_LOADING = "ADMIN_BRAND_LOADING";
export const ADMIN_BRAND_LOADED = "ADMIN_BRAND_LOADED";

export const ADMIN_SINGLEBRAND_LOADING = "ADMIN_SINGLEBRAND_LOADING";
export const ADMIN_SINGLEBRAND_LOADED = "ADMIN_SINGLEBRAND_LOADED";



export const ADMIN_FLAGBRAND_LOADING = "ADMIN_FLAGBRAND_LOADING";
export const ADMIN_FLAGBRAND_LOADED = "ADMIN_FLAGBRAND_LOADED";


export const ADMIN_INFLUENCERS_LOADING = "ADMIN_INFLUENCERS_LOADING";
export const ADMIN_INFLUENCERS_LOADED = "ADMIN_INFLUENCERS_LOADED";

export const ADMIN_SINGLEINFLUENCERS_LOADING = "ADMIN_SINGLEINFLUENCERS_LOADING";
export const ADMIN_SINGLEINFLUENCERS_LOADED = "ADMIN_SINGLEINFLUENCERS_LOADED";

export const ADMIN_FLAGINFLUENCERS_LOADING = "ADMIN_FLAGINFLUENCERS_LOADING";
export const ADMIN_FLAGINFLUENCERS_LOADED = "ADMIN_FLAGINFLUENCERS_LOADED";




export const SENDING_JOB_REQUEST = "SENDING_JOB_REQUEST";
export const SENT_JOB_REQUEST= "SENT_JOB_REQUEST";


export const NOTIFICATION_LOADED="NOTIFICATION_LOADED";
    



export const ADMIN_CAMPAIGNS_LENGTH_LOADED="ADMIN_CAMPAIGNS_LENGTH_LOADED"
export const ADMIN_CAMPAIGNS_LENGTH_LOADING="ADMIN_CAMPAIGNS_LENGTH_LOADING"


export const ADMIN_INFLUENCERS_LENGTH_LOADED="ADMIN_INFLUENCERS_LENGTH_LOADED"
export const ADMIN_INFLUENCERS_LENGTH_LOADING="ADMIN_INFLUENCERS_LENGTH_LOADING"


export const ADMIN_BRANDS_LENGTH_LOADED="ADMIN_BRANDS_LENGTH_LOADED"
export const ADMIN_BRANDS_LENGTH_LOADING="ADMIN_BRANDS_LENGTH_LOADING"





/** END ADMIN TYPES **/